import "./globals.css";
import type { Metadata } from "next";
import { Inter, Dancing_Script } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { StateProvider } from "@/components/providers/StateProvider";
import DialogProvider from "@/components/providers/DialogProvider";
import { SocketProvider } from "@/components/providers/SocketProvider";

const inter = Inter({ subsets: ["latin"] });
const dancingScript = Dancing_Script({
  subsets: ["latin"],
  variable: "--font-dancing-script",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${dancingScript.variable}`}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <StateProvider>
            <SocketProvider>
              <DialogProvider>
                <Toaster />
                {children}
              </DialogProvider>
            </SocketProvider>
          </StateProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
